
blank_issues_enabled: false
contact_links:
  - name: Discussion
    url: https://github.com/Ritik5Prasad/react-native-vpn-detector/discussions/new
    about: Anything that isn't an issue but needs a discussion.